name: Run pytest
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: pip install pytest
      - name: Run pytest
        run: pytest
on:
  pull_request:
    branches:
    - main
